### PR TITLE
Update download_contextual_imagery.py

### PR DESCRIPTION
**Pull request by fedriani**
changing from 200 arcsec to 1000 arcsec

### CODE REVIEW

**Comment by pkgw** [comment]
@fedriani Please let me know if you have any trouble updating the data files!

Also, for project tracking purposes, it's helpful if you edit the messages associated with your commits and pull requests away from the default, to have a bit more detail about the purpose of whatever change you're making. In this case, e.g., "Increase the default size of the contextual imagery" instead of "Update download_contextual_imagery.py".

**Comment by fedriani** [comment]
> @fedriani Please let me know if you have any trouble updating the data files!
> 
> Also, for project tracking purposes, it's helpful if you edit the messages associated with your commits and pull requests away from the default, to have a bit more detail about the purpose of whatever change you're making. In this case, e.g., "Increase the default size of the contextual imagery" instead of "Update download_contextual_imagery.py".

@pkgw absolutely. I forgot this time to update the headline. I actually realised that I did not need to change the size there, I could have done it locally.

I actually tried to run the 2MASS script and could not get it to work.  Maybe I am too dumb but I just run the python script in my terminal. I will play a bit more around it.

**Comment by pkgw** [comment]
@fedriani It would be good to make sure that you're able to generate imagery yourself, so it will be worthwhile to work through. What command are you running and what error message(s) are you getting?

**Comment by fedriani** [comment]
> @fedriani It would be good to make sure that you're able to generate imagery yourself, so it will be worthwhile to work through. What command are you running and what error message(s) are you getting?

I got it working, @pkgw . I just need a few missing packages (the classic). I actually increased the size to 2000arcsec. However, with this size, we lose plenty of resolution. How do we increase the size of the image keeping the greatest resolution?

**Comment by fedriani** [comment]
I think I know why we are losing resolution. It seems that the image size is always 300pix no matter how many arcsec one retrieves. Is there any way to create bigger images size in pixels? We can arrive to a compromise between image_size/weight/resolution.

Thanks!

**Comment by pkgw** [comment]
@fedriani These settings are determined by the SkyView functionality in astroquery, [documented here](https://astroquery.readthedocs.io/en/latest/api/astroquery.skyview.SkyViewClass.html#astroquery.skyview.SkyViewClass.get_images). It looks like there is a "pixels" argument that can be changed.

Note, however, that these services often have limits, so that if you try to download too large of an image it may reject your request or silently reduce the size.

**Pull request merged**
